name: 'Deploy Terraform on AWS'

on:
  workflow_dispatch:
    inputs:
      makefile:
        description: 'Colocar accion del make'
        required: true
        default: 'plan'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: aws

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
        
    - name: Terraform Execution
      run: make ${{github.event.inputs.makefile}}
      working-directory: ./aws_eks_terraform
